version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432 # make sure you don't have another container running on 5432

    environment:
      - POSTGRES_DB=chaiDB
      - POSTGRES_USER=chaiaurcode
      - POSTGRES_PASSWORD=chaiaurcode

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

      # connection url: postgresql://chaiaurcode:chaiaurcode@localhost:5432/chaiDB
      # docker-compose up -d
      # npx prisma migrate dev --name add-status-column
